import express from "express";
import path from "path";
import { fileURLToPath } from "url";
import dotenv from "dotenv";
import { GoogleGenAI } from "@google/genai";
import { createServer as createViteServer } from "vite";

dotenv.config();

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();
const PORT = 3000;

app.use(express.json({ limit: "10mb" }));

// Helper to wrap raw 16-bit PCM (little-endian) into a standard WAV file container
function pcmToWavBuffer(pcmBuffer: Buffer, sampleRate = 24000, numChannels = 1, bitsPerSample = 16): Buffer {
  // Check if buffer is already a valid WAV (starts with 'RIFF')
  if (pcmBuffer.length >= 12 && pcmBuffer.toString("ascii", 0, 4) === "RIFF" && pcmBuffer.toString("ascii", 8, 12) === "WAVE") {
    return pcmBuffer;
  }

  const byteRate = sampleRate * numChannels * (bitsPerSample / 8);
  const blockAlign = numChannels * (bitsPerSample / 8);
  const dataSize = pcmBuffer.length;
  const header = Buffer.alloc(44);

  // RIFF chunk descriptor
  header.write("RIFF", 0);
  header.writeUInt32LE(36 + dataSize, 4);
  header.write("WAVE", 8);

  // fmt sub-chunk
  header.write("fmt ", 12);
  header.writeUInt32LE(16, 16); // Subchunk1Size (16 for PCM)
  header.writeUInt16LE(1, 20); // AudioFormat (1 for PCM)
  header.writeUInt16LE(numChannels, 22);
  header.writeUInt32LE(sampleRate, 24);
  header.writeUInt32LE(byteRate, 28);
  header.writeUInt16LE(blockAlign, 32);
  header.writeUInt16LE(bitsPerSample, 34);

  // data sub-chunk
  header.write("data", 36);
  header.writeUInt32LE(dataSize, 40);

  return Buffer.concat([header, pcmBuffer]);
}

// Health check
app.get("/api/health", (_req, res) => {
  res.json({ status: "ok", model: "gemini-3.1-flash-tts-preview" });
});

// TTS Generation API
app.post("/api/tts", async (req, res) => {
  try {
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      return res.status(400).json({
        error: "GEMINI_API_KEY environment variable is missing. Please configure your key in Settings > Secrets.",
      });
    }

    const {
      text,
      voice = "Charon", // 'Charon' (deep, dramatic), 'Fenrir', 'Kore', 'Puck', 'Zephyr'
      tone = "dramatic",
      targetSeconds = 12,
    } = req.body;

    if (!text || typeof text !== "string" || text.trim().length === 0) {
      return res.status(400).json({ error: "Text is required for voiceover generation." });
    }

    const ai = new GoogleGenAI({
      apiKey,
      httpOptions: {
        headers: {
          "User-Agent": "aistudio-build",
        },
      },
    });

    // Detailed prompt framing for Gemini TTS to speak at the desired 12-second pace with Bengali cadence
    let tonePrompt = "Speak in a deep, resonant, somber, and dramatic apocalyptic tone with gravitas.";
    if (tone === "somber") {
      tonePrompt = "Speak in a calm, reflective, melancholic, and poignant tone.";
    } else if (tone === "urgent") {
      tonePrompt = "Speak in an intense, urgent, warning tone with heightened tension.";
    } else if (tone === "inspirational") {
      tonePrompt = "Speak in a majestic, awe-inspiring, and profound tone.";
    }

    const prompt = `Perform this voiceover in authentic Bengali with clear pronunciation.
Style: ${tonePrompt}
Pacing: Measured and slow, taking deliberate pauses at ellipses (…) and punctuation to fit a target duration of approximately ${targetSeconds} seconds.

Bengali Script:
${text.trim()}`;

    const response = await ai.models.generateContent({
      model: "gemini-3.1-flash-tts-preview",
      contents: [{ parts: [{ text: prompt }] }],
      config: {
        responseModalities: ["AUDIO"],
        speechConfig: {
          voiceConfig: {
            prebuiltVoiceConfig: { voiceName: voice },
          },
        },
      },
    });

    const candidate = response.candidates?.[0];
    const audioPart = candidate?.content?.parts?.find(
      (p) => p.inlineData && p.inlineData.data
    );

    if (!audioPart || !audioPart.inlineData?.data) {
      return res.status(500).json({
        error: "No audio generated by the TTS model. Please try again.",
      });
    }

    const rawBase64 = audioPart.inlineData.data;
    const rawBuffer = Buffer.from(rawBase64, "base64");

    // Convert raw PCM to standard playable WAV buffer
    const wavBuffer = pcmToWavBuffer(rawBuffer, 24000, 1, 16);
    const wavBase64 = wavBuffer.toString("base64");

    // Calculate approximate duration in seconds based on 24000Hz 16-bit mono PCM
    const durationSeconds = rawBuffer.length / (24000 * 2);

    return res.json({
      success: true,
      audioBase64: wavBase64,
      mimeType: "audio/wav",
      durationSeconds: Number(durationSeconds.toFixed(2)),
      sampleRate: 24000,
      voiceUsed: voice,
    });
  } catch (err: unknown) {
    console.error("TTS generation error:", err);
    const message = err instanceof Error ? err.message : "Failed to generate voiceover";
    return res.status(500).json({ error: message });
  }
});

async function startServer() {
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (_req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on http://0.0.0.0:${PORT}`);
  });
}

startServer();
